server:
  port: 8088

# datasource
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    name: dev
    url: jdbc:mysql://127.0.0.1:3306/db_huawei?serverTimezone=UTC&autoReconnect=true&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: 123456
    initialSize: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    useGlobalDataSourceStat: true

  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # 连接密码
    password: 123456
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 500
        # 连接池中的最小空闲连接
        min-idle: 0
    lettuce:
      shutdown-timeout: 0
    # 连接超时时间（毫秒）
    timeout: 1000

#showSql
logging:
  level:
    com:
      huaweisoft:
        huawei5g: debug

mybatis-plus:
  type-aliases-package: com.huaweisoft.huawei5g.model
  mapper-locations: classpath:mapper/*.xml
  global-config:
    id-type: 0
    db-column-underline: true
    capital-mode: true
